## slope 'base' container.  Installs system and R libraries.
## SLOPER base dependencies image.  Installs system libraries, R libraries, and others.
## Top image extends this image and copies the source code for the app

ARG cloud_version=aws

# Install latest version of rocker image
FROM rocker/shiny:4.3 AS base

# Load general use libraries
# Keep gettext-base for MultiProbe
RUN apt-get update && apt-get install -y \
    sudo \
    gettext-base \
    pandoc \
    pandoc-citeproc \
    libssl-dev \
    libcurl4-openssl-dev \
    libcairo2-dev \
    libxt-dev \
    libssh2-1-dev \
    libhiredis-dev \
    libgsl-dev \
    cmake \
    libzmq3-dev \
    libxml2-dev \
    libharfbuzz-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libfribidi-dev \
    libcurl3-gnutls \
	  vim python3-venv \
	  automake

USER root

# Keep for MultiProbe, direct to correct url
WORKDIR /srv/shiny-server/slope

# pre-install renv
ENV RENV_VERSION 1.0.3
ENV RENV_WATCHDOG_ENABLED FALSE

RUN echo "Installing remotes and renv..."

RUN R -e "install.packages('remotes', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "remotes::install_version('renv', version = '${RENV_VERSION}', repos = c(CRAN = 'https://cloud.r-project.org'))"
RUN R -e "options(renv.config.connect.timeout = 1000L)"
RUN R -e "options(renv.config.connect.retry = 3L)"

# dependencies
COPY renv.lock .
# Contains local repos
COPY renv ./renv

## Bioconductor is silly
RUN R -e "install.packages('BiocManager')"
RUN R -e "BiocManager::install('Biobase')"
RUN R -e "BiocManager::install('BiocGenerics')"
RUN R -e "BiocManager::install('BiocVersion')"
RUN R -e "BiocManager::install('BiocParallel')"
RUN R -e "BiocManager::install('mixOmics')"
RUN R -e "BiocManager::install('pcaMethods')"
RUN R -e "BiocManager::install('plsmod')"

FROM base AS aws

RUN echo "Building MultiProbe image."

# install all packages listed in renv.lock
RUN R -e 'renv::restore()'

## Keep for MultiProbe AWS
RUN R -e "install.packages('aws.s3')"
RUN R -e "install.packages('aws.ec2metadata')"

FROM base AS map

RUN echo "Building MAP image."

# install all packages listed in renv.lock
RUN R -e "options(repos=c('CRAN' = 'https://cloud.r-project.org', BiocManager::repositories()));renv::restore()"

RUN R -e "remotes::install_local('./renv/local/mapdataaccess-lib.zip')" 

FROM ${cloud_version} AS final

# python and requirements
COPY requirements.txt .
RUN python3 -m venv /venv
RUN /venv/bin/pip install --upgrade pip
RUN /venv/bin/pip install -r requirements.txt
